### ISSUE TITLE
поправити лінки на сторінці API

### ISSUE THREAD

**Issue by GS-0001** [OPORA/publicwhip-vinnitsa#1]
**тут https://vinnytsia.rada4you.org/help/data текст посилання не відповідає самій адресі посилання**
*розділ JSON*
- [x] https://vinnytsia.rada4you.org/api/division.json?division=1

*розділ CSV*
- [x] https://vinnytsia.rada4you.org/api/division.csv?division=1&filter=info

**Comment by beastie87** [comment]
@GS-0001  вибач не зрузомів)

**Comment by GS-0001** [comment]
проклікай лінки на сторінці api. там не ті набори завантажуються

**Comment by beastie87** [comment]
@GS-0001  дякую тепр зрозумів)
